const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const ALIGN_DIR = path.join(ROOT, "alignment");

// Core identity artefacts to track
const ID_FILES = [
  "paul_desai_active_mirror.md",
  "IDENTITY_STORY_MINIFIED.md",
  "IDENTITY_STORY.md",
  "system.md",
  "now.md",
  "INJECT.md",
  "BOOT.md",
  "identity.json",
  "schema.jsonld",
  "llms.txt",
  "README.md",
  "LICENSE",
  "identity_capsule.jsonld",
  path.join("spec", "Reflection_Chain_Manifest_v1.0.md"),
];

function detectQuarter(date) {
  const year = date.getUTCFullYear();
  const month = date.getUTCMonth(); // 0–11
  const q = Math.floor(month / 3) + 1;
  return { year, quarter: q };
}

function fileExists(rel) {
  return fs.existsSync(path.join(ROOT, rel));
}

function readFile(rel) {
  return fs.readFileSync(path.join(ROOT, rel), "utf8");
}

function hasVaultId(content) {
  return /VaultID\s*:\s*AMOS:\/\//i.test(content);
}

function hasGlyphSig(content) {
  return /(glyphsig|GlyphSig)/.test(content);
}

function buildTableRow(rel) {
  if (!fileExists(rel)) {
    return `| \`${rel}\` | ✖ missing | ✖ | ✖ | not found in repo |`;
  }

  const content = readFile(rel);
  const vault = hasVaultId(content) ? "✓" : "✖";
  const glyph = hasGlyphSig(content) ? "✓" : "✖";
  const status = vault === "✓" && glyph === "✓" ? "✓ ok" : "⚠ check";

  return `| \`${rel}\` | ${status} | ${vault} | ${glyph} | automated scan |`;
}

function buildHeader(year, quarter, rows) {
  return [
    `# ⟡ Alignment Snapshot — ${year} Q${quarter}`,
    "VaultID: AMOS://[Unknown — update not fetched]",
    "GlyphSig: [Unknown — update not fetched]",
    "**Repository:** MirrorDNA-Reflection-Protocol/active-mirror-identity  ",
    "**Handle:** `~active-mirror-paul`  ",
    "**Generated By:** Codex-Coder (Automated)  ",
    "**Continuity Mode:** Truth > Fluency · Provenance Checked",
    "",
    "---",
    "",
    "## 1. Identity Artefact Index  ",
    "| File | Status | VaultID Present | GlyphSig Present | Notes |",
    "|------|--------|-----------------|------------------|-------|",
    rows,
    "",
    "---",
    "",
    "## 2. Notes",
    "",
    "- This file was generated automatically by `tools/generate_alignment_snapshot.js`.",
    "- It does not replace manual Vault review; it is an external alignment log.",
    "- Any ✖ / ⚠ rows should be reviewed and corrected in a separate commit.",
    "",
    "---",
    "",
    "## 3. Drift Status (Automated Heuristic)",
    "",
    "- Drift Level: 0 if all required files exist and show VaultID + GlyphSig, otherwise > 0.",
    "",
  ].join("\n");
}

function generateSnapshot() {
  const now = new Date();
  const { year, quarter } = detectQuarter(now);
  const filename = `alignment-snapshot-${year}-Q${quarter}.md`;

  if (!fs.existsSync(ALIGN_DIR)) {
    fs.mkdirSync(ALIGN_DIR, { recursive: true });
  }

  const rows = ID_FILES.map(buildTableRow).join("\n");
  const header = buildHeader(year, quarter, rows);

  const filepath = path.join(ALIGN_DIR, filename);
  fs.writeFileSync(filepath, header, "utf8");

  console.log(`Generated ${path.relative(ROOT, filepath)}`);
}

generateSnapshot();
